version: "3.1"
services:
  mirth-connect:
    image: nextgenhealthcare/connect:latest
    container_name: 'mirth-connect'
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 1000-1100:1000-1100
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent Postgres data form mirth

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672" # RabbitMQ standard port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data storage for RabbitMQ

  portainer:
    image: portainer/portainer-ce:latest
    container_name: 'portainer'
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data # Persistent portainer data

  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: abi-metadata
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
  
  mysql-handler:
    #image: ghcr.io/abi-interoperability-thesis/mysql-webservice:latest
    build: ../mysql-webservice
    container_name: 'mysql-webservice'
    environment:
      - PORT=3000
      - ENV=prod
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql-container
      - DB_NAME=abi-metadata
    ports:
    - "3002:3000"
    depends_on:
      - mysql-db

  abi-webapp:
    image: ghcr.io/abi-interoperability-thesis/abi-interoperability-webapp:latest
    container_name: 'abi-webapp'
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_ENV=prod
      - REACT_APP_MYSQL_SERVICE_ENDPOINT=http://127.0.0.1:3002
      - REACT_APP_MIRTH_SERVICE_ENDPOINT=http://127.0.0.1:3000
      - REACT_APP_RABBITMQ_SERVICE_ENDPOINT=http://127.0.0.1:3001
      - REACT_APP_MIRTH_ENDPOINT=http://mirth-connect
      - REACT_APP_MIRTH_ENDPOINT_DOCS=http://127.0.0.1
    depends_on:
      - mysql-webservice
      - mirth-api-webservice
      - message-queue-webservice

  mirth-api-handler:
    image: ghcr.io/abi-interoperability-thesis/mirth-api-webservice:latest
    container_name: 'mirth-api-webservice'
    environment:
      - PORT=3000
      - MIRTH_USERNAME=admin
      - MIRTH_PASSWORD=admin
      - ENV=prod
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=abi-metadata
      - MIRTH_ENDPOINT=https://mirth-connect:8443
      - MYSQL_SERVICE_ENDPOINT=http://mysql-webservice:3000
    ports:
      - "3000:3000"

  message-handler:
      image: ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:latest
      container_name: 'message-queue-webservice'
      environment:
        - PORT=3000
        - ENV=local
        - RABBIT_USERNAME=guest
        - RABBIT_PASSWORD=guest
        - RABBIT_MQ_HOST=rabbitmq:5672
        - MYSQL_SERVICE_ENDPOINT=http://mysql-webservice:3000
      depends_on:
        - rabbitmq
      ports:
        - "3001:3000"

volumes:
  portainer_data:
  rabbitmq_data:
  postgres_data:
  mysql_data: