version: "3.1"
services:
  mirth-connect:
    image: nextgenhealthcare/connect
    container_name: 'mirth-connect'
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    depends_on:
      - db
  db:
    image: postgres
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent Postgres data form mirth

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672" # RabbitMQ standard port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data storage for RabbitMQ

  portainer:
    image: portainer/portainer-ce:latest
    container_name: 'portainer'
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data # Persistent portainer data

  message-handler:
    build: ./MessageHandler
    container_name: 'message-handler'
  
volumes:
  portainer_data:
  rabbitmq_data:
  postgres_data: