version: "3.1"
services:
  mirth-connect:
    image: nextgenhealthcare/connect:latest
    container_name: 'mirth-connect'
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 1000-1100:1000-1100
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent Postgres data for mirth db

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672" # RabbitMQ standard port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data storage for RabbitMQ

  portainer:
    image: portainer/portainer-ce:latest
    container_name: 'portainer'
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # Persistent portainer data

  message-handler:
    build: ./rabbitmq-webservice
    container_name: 'message-queue-webservice'
    environment:
      - PORT=3000
      - ENV=local # for connection with local rabbitmq container. prod for connection with vm rabbitmq container
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    depends_on:
      - rabbitmq
    ports:
      - "3001:3000"

  mirth-api-handler:
    build: ./mirth-api-webservice
    container_name: 'mirth-api-webservice'
    environment:
      - PORT=3000
      - MIRTH_USERNAME=admin
      - MIRTH_PASSWORD=123
      - ENV=prod # prod for connection with mirth connect container
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=abi-metadata
    ports:
      - "3000:3000"

  mysql-handler:
    build: ./mysql-webservice
    container_name: 'mysql-webservice'
    environment:
      - PORT=3000
      - ENV=prod # prod for connection with mysql container
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=abi-metadata
    ports:
      - "3002:3000"

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: abi-metadata
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

# Volumes declaration
volumes:
  portainer_data:
  rabbitmq_data:
  postgres_data:
  mysql_data:
